spring:
  application:
    name: java-projeto-assitencia-tecnica

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=logos;encrypt=true;trustServerCertificate=true
    username: sa
    password: 123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: false
    open-in-view: true
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    locations: classpath:db/migration

  logging:
    level:
      root: trace
      br.com.feSchulz: DEBUG

  spring-doc:
    paths-to-match: /api/**/v1/**
